# Generated by Django 5.2.16 on 2026-07-11 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='health_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='health.healthrecord'),
        ),
    ]
