# Generated by Django 5.2.16 on 2026-07-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_health_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_bird_sale',
            field=models.BooleanField(default=False),
        ),
    ]
