# Generated by Django 5.2.16 on 2026-07-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_code',
            field=models.CharField(blank=True, help_text='Auto-generated (e.g. BRO-2026-001) if left blank.', max_length=50, unique=True),
        ),
    ]
