# Generated by Django 5.2.16 on 2026-07-11 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('record_type', models.CharField(choices=[('VACCINATION', 'Vaccination'), ('MEDICATION', 'Medication'), ('TREATMENT', 'Treatment')], max_length=12)),
                ('name', models.CharField(help_text='Vaccine / drug / treatment name.', max_length=150)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('administered_by', models.CharField(blank=True, max_length=150)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='inventory.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bird_type', models.CharField(blank=True, choices=[('LAYER', 'Layer'), ('BROILER', 'Broiler'), ('BREEDER', 'Breeder')], help_text='Leave blank to apply to any bird type.', max_length=10)),
                ('vaccine_name', models.CharField(max_length=150)),
                ('day_of_age', models.PositiveIntegerField(help_text='Age in days when this vaccine is due.')),
                ('notes', models.TextField(blank=True)),
                ('breed', models.ForeignKey(blank=True, help_text='Optional: restrict to a specific breed.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedules', to='core.breed')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('day_of_age', 'vaccine_name'),
            },
        ),
    ]
