# Generated by Django 5.2.16 on 2026-07-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationschedule',
            name='bird_type',
            field=models.CharField(blank=True, help_text='Tick the bird types this vaccine applies to. Leave all unticked to apply to any bird type.', max_length=40),
        ),
    ]
